CREATE TABLE [dbo].[PLANET]
(
	[PlanetId] INT IDENTITY (1, 1) NOT NULL,
    [Galaxy] SMALLINT NOT NULL, 
    [System] SMALLINT NOT NULL, 
    [Place] SMALLINT NOT NULL,
	[PlayerId] INT NOT NULL,
	[DateCreation] DATE NOT NULL,
	CONSTRAINT [PK_PLANET] PRIMARY KEY CLUSTERED ([PlanetId] ASC),
	CONSTRAINT [FK_PLAYER_PLANET] FOREIGN KEY (PlayerId) REFERENCES [dbo].[PLAYER] (PlayerId),
)
