CREATE TABLE [dbo].[PLAYER]
(
	[PlayerId] INT IDENTITY (1, 1) NOT NULL,
    [Name] NCHAR(200) NULL,
	[IsAFK] BIT NULL DEFAULT NULL , 
    [IsVacation] BIT NULL DEFAULT NULL , 
    [InternalIdOR] INT NULL, 
    [IsQuestPlayer] BIT NULL, 
    CONSTRAINT [PK_PLAYER] PRIMARY KEY CLUSTERED ([PlayerId] ASC),
)
